name: Move Assigned Card
on:
  issues:
    types: 
      - assigned
      
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with: 
          project: Softree-App
          column: In progress
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
